version: 0.9.0-dev-{build}
branches:
  only:
  - master
image: Visual Studio 2019
configuration: Release
before_build:
- ps: '& .\appveyor-prebuild.ps1'
build:
  project: TacacsPlusCore.sln
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  parallel: true
  verbosity: normal
deploy:
- provider: NuGet
  api_key:
    secure: SeD4hVLZpsEeexlDTYN43yUm0TdwrlqIOvnUHwjbizuc+pK04sl7YWUdi9JBgRti
notifications:
- provider: Email
  to:
  - petrsnd@gmail.com
  subject: TacacsPlusCore build is failing
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
