version: 0.9.0-dev-{build}
image: Visual Studio 2019
configuration: Release
before_build:
- ps: '& .\appveyor-prebuild.ps1'
build:
  project: TacacsPlusCore.sln
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  parallel: true
  verbosity: normal
deploy:
- provider: NuGet
  api_key:
    secure: IV72kyxJEsCRH4LAh0pZLozb6jznTZkCn7l/8qA2YxNajQ4Z5kQUtUAsabF9SxLf
notifications:
- provider: Email
  to:
  - petrsnd@gmail.com
  subject: TacacsPlusCore build is failing
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
